# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.6, 3.7 and PyPy3 on Xenial Linux"
      python:
        - "3.6"
        - "3.7"           # this works for Linux but is ignored on macOS or Windows
	- "pypy3"
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode11  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python  # this install takes at least 1 min 30 sec
        - python -m pip install --upgrade pip
	- python -m pip install PyInstaller
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install .
  - pip3 install pytest
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - pytest
  - ./build_pyinstaller_win.sh
